### ISSUE TITLE
Cannot include usbd-audio as crate in cargo manifest

### ISSUE THREAD

**Issue by backtail** [kiffie/usbd-audio#1]
When I try to include the `usbd-audio` crate in my Cargo.toml, rust-analyzer starts to use 100% of my CPU and never finds any metadata. 

My current rust setup:

``` shell
$ rustc --version
$ rustc 1.64.0 (a55dd71d5 2022-09-19)
```

I use the rust-analyzer in the most recent release from the VS Code marketplace: `rust-analyzer version: 0.3.1277-standalone`

I want to use your library in a somewhat big project, where I already included a dozen crates without a problem. Any clue, on what it might be?

**Comment by kiffie** [comment]
I am using rust-analyzer version  0.3.1277 with vs-code as well but with rustc-1.65 and rustc-1.67-nighly. It works. I am using it in a project with about 20 crates, too. So, unfortunately, I do not know why rust-analyzer hangs in your project.

Maybe, something is wrong with the rust-analyzer settings in `.vscode/settings.json`?

Does `cargo build` or `cargo check` work?

**Comment by backtail** [comment]
Using `rustc-1.64` was the problem. `rustc-1.65` works!

**Comment by kiffie** [comment]
Great. Problem solved.
